// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualStudioScreenshot
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVisualStudioScreenshotPackageString = "a512387e-6f49-44c9-afe6-bb6db4b32c05";
        public static Guid guidVisualStudioScreenshotPackage = new Guid(guidVisualStudioScreenshotPackageString);

        public const string guidVisualStudioScreenshotPackageCmdSetString = "f2f7beed-cbd2-40e2-956a-e533083b9dbc";
        public static Guid guidVisualStudioScreenshotPackageCmdSet = new Guid(guidVisualStudioScreenshotPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CaptureImageMenuGroup = 0x1000;
        public const int CaptureImageMenu = 0x2000;
        public const int CaptureImageGroup = 0x1020;
        public const int CaptureMainWindowId = 0x0100;
        public const int CaptureActiveWindowId = 0x0200;
    }
}